// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sls.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Log struct {
	Time                 *uint32        `protobuf:"varint,1,req,name=Time" json:"Time,omitempty"`
	Contents             []*Log_Content `protobuf:"bytes,2,rep,name=Contents" json:"Contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b499e77351ce2e, []int{0}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Log) GetContents() []*Log_Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Log_Content struct {
	Key                  *string  `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log_Content) Reset()         { *m = Log_Content{} }
func (m *Log_Content) String() string { return proto.CompactTextString(m) }
func (*Log_Content) ProtoMessage()    {}
func (*Log_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b499e77351ce2e, []int{0, 0}
}

func (m *Log_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log_Content.Unmarshal(m, b)
}
func (m *Log_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log_Content.Marshal(b, m, deterministic)
}
func (m *Log_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log_Content.Merge(m, src)
}
func (m *Log_Content) XXX_Size() int {
	return xxx_messageInfo_Log_Content.Size(m)
}
func (m *Log_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Log_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Log_Content proto.InternalMessageInfo

func (m *Log_Content) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Log_Content) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type LogTag struct {
	Key                  *string  `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogTag) Reset()         { *m = LogTag{} }
func (m *LogTag) String() string { return proto.CompactTextString(m) }
func (*LogTag) ProtoMessage()    {}
func (*LogTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b499e77351ce2e, []int{1}
}

func (m *LogTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogTag.Unmarshal(m, b)
}
func (m *LogTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogTag.Marshal(b, m, deterministic)
}
func (m *LogTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogTag.Merge(m, src)
}
func (m *LogTag) XXX_Size() int {
	return xxx_messageInfo_LogTag.Size(m)
}
func (m *LogTag) XXX_DiscardUnknown() {
	xxx_messageInfo_LogTag.DiscardUnknown(m)
}

var xxx_messageInfo_LogTag proto.InternalMessageInfo

func (m *LogTag) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *LogTag) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type LogGroup struct {
	Logs                 []*Log    `protobuf:"bytes,1,rep,name=Logs" json:"Logs,omitempty"`
	Reserved             *string   `protobuf:"bytes,2,opt,name=Reserved" json:"Reserved,omitempty"`
	Topic                *string   `protobuf:"bytes,3,opt,name=Topic" json:"Topic,omitempty"`
	Source               *string   `protobuf:"bytes,4,opt,name=Source" json:"Source,omitempty"`
	LogTags              []*LogTag `protobuf:"bytes,6,rep,name=LogTags" json:"LogTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogGroup) Reset()         { *m = LogGroup{} }
func (m *LogGroup) String() string { return proto.CompactTextString(m) }
func (*LogGroup) ProtoMessage()    {}
func (*LogGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b499e77351ce2e, []int{2}
}

func (m *LogGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogGroup.Unmarshal(m, b)
}
func (m *LogGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogGroup.Marshal(b, m, deterministic)
}
func (m *LogGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogGroup.Merge(m, src)
}
func (m *LogGroup) XXX_Size() int {
	return xxx_messageInfo_LogGroup.Size(m)
}
func (m *LogGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_LogGroup.DiscardUnknown(m)
}

var xxx_messageInfo_LogGroup proto.InternalMessageInfo

func (m *LogGroup) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *LogGroup) GetReserved() string {
	if m != nil && m.Reserved != nil {
		return *m.Reserved
	}
	return ""
}

func (m *LogGroup) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *LogGroup) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *LogGroup) GetLogTags() []*LogTag {
	if m != nil {
		return m.LogTags
	}
	return nil
}

func init() {
	proto.RegisterType((*Log)(nil), "mbxc.auth.v1.Log")
	proto.RegisterType((*Log_Content)(nil), "mbxc.auth.v1.Log.Content")
	proto.RegisterType((*LogTag)(nil), "mbxc.auth.v1.LogTag")
	proto.RegisterType((*LogGroup)(nil), "mbxc.auth.v1.LogGroup")
}

func init() { proto.RegisterFile("sls.proto", fileDescriptor_c6b499e77351ce2e) }

var fileDescriptor_c6b499e77351ce2e = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0x6c, 0x9a, 0x26, 0xa3, 0x82, 0x0e, 0x45, 0xd6, 0x9e, 0x42, 0x41, 0xc8, 0x69,
	0xb1, 0x82, 0x7f, 0x40, 0x0f, 0x1e, 0xdc, 0xd3, 0x1a, 0x3c, 0x78, 0x5b, 0xe3, 0xb2, 0x06, 0xda,
	0x4e, 0xc8, 0x26, 0x45, 0xcf, 0xfe, 0x1c, 0xff, 0xa4, 0x74, 0x13, 0x8b, 0xd0, 0x4b, 0x6f, 0xef,
	0x9b, 0x79, 0x33, 0xef, 0x41, 0xe6, 0x57, 0x5e, 0x36, 0x2d, 0x75, 0x84, 0xa7, 0xeb, 0xb7, 0xcf,
	0x4a, 0x9a, 0xbe, 0xfb, 0x90, 0xdb, 0xe5, 0xe2, 0x9b, 0x01, 0x57, 0xe4, 0x10, 0x21, 0x2e, 0xeb,
	0xb5, 0x15, 0x2c, 0x8f, 0x8a, 0x33, 0x1d, 0x34, 0xde, 0x41, 0xfa, 0x40, 0x9b, 0xce, 0x6e, 0x3a,
	0x2f, 0xa2, 0x9c, 0x17, 0x27, 0xb7, 0x57, 0xf2, 0xff, 0xb1, 0x54, 0xe4, 0xe4, 0xe8, 0xd0, 0x7b,
	0xeb, 0x7c, 0x09, 0xd3, 0x51, 0xe3, 0x39, 0xf0, 0x27, 0xfb, 0x15, 0x9e, 0x66, 0x7a, 0x27, 0x71,
	0x06, 0x93, 0x17, 0xb3, 0xea, 0xad, 0x88, 0xc2, 0x6c, 0x80, 0xc5, 0x0d, 0x24, 0x8a, 0x5c, 0x69,
	0xdc, 0xd1, 0x17, 0x3f, 0x0c, 0x52, 0x45, 0xee, 0xb1, 0xa5, 0xbe, 0xc1, 0x6b, 0x88, 0x15, 0x39,
	0x2f, 0x58, 0x28, 0x79, 0x71, 0x50, 0x52, 0x87, 0x35, 0xce, 0x21, 0xd5, 0xd6, 0xdb, 0x76, 0x6b,
	0xdf, 0x45, 0x94, 0xb3, 0x22, 0xd3, 0x7b, 0xde, 0xa5, 0x94, 0xd4, 0xd4, 0x95, 0xe0, 0x61, 0x31,
	0x00, 0x5e, 0x42, 0xf2, 0x4c, 0x7d, 0x5b, 0x59, 0x11, 0x87, 0xf1, 0x48, 0x28, 0x61, 0x3a, 0xf4,
	0xf5, 0x22, 0x09, 0x99, 0xb3, 0x83, 0xcc, 0xd2, 0x38, 0xfd, 0x67, 0xba, 0x9f, 0xbc, 0x72, 0xd3,
	0xd4, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x62, 0xba, 0x0e, 0x20, 0x86, 0x01, 0x00, 0x00,
}
